name: em_recharge
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - attrs=25.4.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - cfgv=3.5.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - deprecated=1.3.1
  - dill=0.4.0
  - distlib=0.4.0
  - donfig=0.8.1.post1
  - empymod=2.5.2
  - executing=2.2.1
  - filelock=3.20.0
  - fonttools=4.60.1
  - freetype=2.14.1
  - freexl=2.0.0
  - geoana=0.8.0
  - geos=3.14.1
  - geotiff=1.7.4
  - giflib=5.2.2
  - google-crc32c=1.7.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - identify=2.6.15
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipyleaflet=0.20.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_leaflet=0.20.0
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.8.2
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libdeflate=1.25
  - libdlf=0.3.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-core=3.10.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.51
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - llvmlite=0.45.1
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - minizip=4.0.10
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nodeenv=1.9.1
  - numba=0.62.1
  - numcodecs=0.16.1
  - numpy=1.26.4
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.47
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - platformdirs=4.5.0
  - pooch=1.8.2
  - pre-commit=4.5.0
  - proj=9.7.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pymatsolver=0.4.0
  - pyparsing=3.2.5
  - pyproj=3.7.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - rasterio=1.4.3
  - readline=8.2
  - requests=2.32.5
  - rioxarray=0.19.0
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - scooby=0.11.0
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.0
  - stack_data=0.6.3
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - traittypes=0.2.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ukkonen=1.0.1
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - utm=0.7.0
  - virtualenv=20.35.4
  - wcwidth=0.2.14
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wrapt=1.17.3
  - xarray=2025.11.0
  - xerces-c=3.3.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - zarr=3.1.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - curvenote==0.7.2
      - backports-tarfile==1.2.0
      - build==1.3.0
      - cloudpickle==3.1.2
      - curvenote==0.7.2
      - dask==2025.11.0
      - discretize==0.12.0
      - docutils==0.22.3
      - emrecharge==0.0.15
      - fsspec==2025.10.0
      - geopandas==1.1.1
      - id==1.5.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - keyring==25.7.0
      - locket==1.0.0
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - nh3==0.3.2
      - partd==1.4.2
      - properties==0.6.1
      - pyogrio==0.11.1
      - pypng==0.20220715.0
      - pyproject-hooks==1.2.0
      - readme-renderer==44.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==14.2.0
      - scikit-fmm==2023.4.2
      - shapely==2.1.2
      - simpeg==0.25.0
      - toolz==1.1.0
      - twine==6.2.0
      - vectormath==0.2.2
      - verde==1.8.1
prefix: /Users/sgkang09/anaconda3/envs/em_recharge_test
