name: em_recharge

channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - matplotlib
  - SimPEG=0.18.1
  - ipykernel
  - ipywidgets>=8
  - ipyleaflet
  - dill
  - discretize=0.8.3
  - pooch
  - pre-commit
  - rioxarray
  - xarray
  - zarr
  - pip
  - pip:
      - curvenote
      - emrecharge==0.0.14
